# Generated by Django 3.2.3 on 2021-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=200),
        ),
    ]
